#
# GitHub Actions Workflow
#   reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#

name: Docs Deploy

run-name: ${{ format('Deploy {0}', inputs.environment) }}

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy
        required: true
        type: choice
        options:
          - lionkey.dev
      dry-run:
        description: Don't actually deploy (--dry-run)
        required: false
        default: false
        type: boolean

# We set default permissions (all to none) for all jobs in this workflow
# to adhere to the principle of least privilege,
# and we grant only the necessary permissions at the job level.
# docs: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#defining-access-for-the-github_token-scopes
permissions: {}

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/docs.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      deployment: true
      dry-run: ${{ inputs.dry-run }}
      environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}
